# Generated by Django 5.0.6 on 2024-06-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
