# Generated by Django 5.0.6 on 2024-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_rename_hashtag_tweet_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='delete_tweet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
